/**
 */
package sma.ui.viewmodels.contenedorescaneoviewmodel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import sma.ui.viewmodels.contenedorescaneoviewmodel.util.ContenedorescaneoviewmodelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ContenedorescaneoviewmodelItemProviderAdapterFactory extends ContenedorescaneoviewmodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ContenedorescaneoviewmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorEscaneoViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorEscaneoViewModelItemProvider contenedorEscaneoViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorEscaneoViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorEscaneoViewModelAdapter() {
		if (contenedorEscaneoViewModelItemProvider == null) {
			contenedorEscaneoViewModelItemProvider = new ContenedorEscaneoViewModelItemProvider(this);
		}

		return contenedorEscaneoViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorFallasViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorFallasViewModelItemProvider contenedorFallasViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorFallasViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorFallasViewModelAdapter() {
		if (contenedorFallasViewModelItemProvider == null) {
			contenedorFallasViewModelItemProvider = new ContenedorFallasViewModelItemProvider(this);
		}

		return contenedorFallasViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorSeleccionautoViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorSeleccionautoViewModelItemProvider contenedorSeleccionautoViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ContenedorSeleccionautoViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorSeleccionautoViewModelAdapter() {
		if (contenedorSeleccionautoViewModelItemProvider == null) {
			contenedorSeleccionautoViewModelItemProvider = new ContenedorSeleccionautoViewModelItemProvider(this);
		}

		return contenedorSeleccionautoViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ListaFallasViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListaFallasViewModelItemProvider listaFallasViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorescaneoviewmodel.ListaFallasViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListaFallasViewModelAdapter() {
		if (listaFallasViewModelItemProvider == null) {
			listaFallasViewModelItemProvider = new ListaFallasViewModelItemProvider(this);
		}

		return listaFallasViewModelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (contenedorEscaneoViewModelItemProvider != null) contenedorEscaneoViewModelItemProvider.dispose();
		if (contenedorFallasViewModelItemProvider != null) contenedorFallasViewModelItemProvider.dispose();
		if (contenedorSeleccionautoViewModelItemProvider != null) contenedorSeleccionautoViewModelItemProvider.dispose();
		if (listaFallasViewModelItemProvider != null) listaFallasViewModelItemProvider.dispose();
	}

}
