/**
 */
package sma.ui.viewmodels.contenedorcrudclienteviewmodel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import sma.ui.viewmodels.contenedorcrudclienteviewmodel.util.ContenedorcrudclienteviewmodelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ContenedorcrudclienteviewmodelItemProviderAdapterFactory extends ContenedorcrudclienteviewmodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ContenedorcrudclienteviewmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ClienteViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClienteViewModelItemProvider clienteViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ClienteViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClienteViewModelAdapter() {
		if (clienteViewModelItemProvider == null) {
			clienteViewModelItemProvider = new ClienteViewModelItemProvider(this);
		}

		return clienteViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorCrudClienteViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorCrudClienteViewModelItemProvider contenedorCrudClienteViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorCrudClienteViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorCrudClienteViewModelAdapter() {
		if (contenedorCrudClienteViewModelItemProvider == null) {
			contenedorCrudClienteViewModelItemProvider = new ContenedorCrudClienteViewModelItemProvider(this);
		}

		return contenedorCrudClienteViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDatosPersonalesViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorDatosPersonalesViewModelItemProvider contenedorDatosPersonalesViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDatosPersonalesViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorDatosPersonalesViewModelAdapter() {
		if (contenedorDatosPersonalesViewModelItemProvider == null) {
			contenedorDatosPersonalesViewModelItemProvider = new ContenedorDatosPersonalesViewModelItemProvider(this);
		}

		return contenedorDatosPersonalesViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDatosdelacuentaViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorDatosdelacuentaViewModelItemProvider contenedorDatosdelacuentaViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDatosdelacuentaViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorDatosdelacuentaViewModelAdapter() {
		if (contenedorDatosdelacuentaViewModelItemProvider == null) {
			contenedorDatosdelacuentaViewModelItemProvider = new ContenedorDatosdelacuentaViewModelItemProvider(this);
		}

		return contenedorDatosdelacuentaViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDetalleClienteViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorDetalleClienteViewModelItemProvider contenedorDetalleClienteViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorDetalleClienteViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorDetalleClienteViewModelAdapter() {
		if (contenedorDetalleClienteViewModelItemProvider == null) {
			contenedorDetalleClienteViewModelItemProvider = new ContenedorDetalleClienteViewModelItemProvider(this);
		}

		return contenedorDetalleClienteViewModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorMaestroClienteViewModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorMaestroClienteViewModelItemProvider contenedorMaestroClienteViewModelItemProvider;

	/**
	 * This creates an adapter for a {@link sma.ui.viewmodels.contenedorcrudclienteviewmodel.ContenedorMaestroClienteViewModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenedorMaestroClienteViewModelAdapter() {
		if (contenedorMaestroClienteViewModelItemProvider == null) {
			contenedorMaestroClienteViewModelItemProvider = new ContenedorMaestroClienteViewModelItemProvider(this);
		}

		return contenedorMaestroClienteViewModelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (clienteViewModelItemProvider != null) clienteViewModelItemProvider.dispose();
		if (contenedorCrudClienteViewModelItemProvider != null) contenedorCrudClienteViewModelItemProvider.dispose();
		if (contenedorDatosPersonalesViewModelItemProvider != null) contenedorDatosPersonalesViewModelItemProvider.dispose();
		if (contenedorDatosdelacuentaViewModelItemProvider != null) contenedorDatosdelacuentaViewModelItemProvider.dispose();
		if (contenedorDetalleClienteViewModelItemProvider != null) contenedorDetalleClienteViewModelItemProvider.dispose();
		if (contenedorMaestroClienteViewModelItemProvider != null) contenedorMaestroClienteViewModelItemProvider.dispose();
	}

}
